"""Initial3

Revision ID: 41d6ad80ac73
Revises: 95a703981e4b
Create Date: 2025-12-15 17:04:54.325785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d6ad80ac73'
down_revision: Union[str, None] = '95a703981e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'new_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('new_test', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

def check() -> None:
    """check for sync between the tenants and metadata"""
    "pass"
    