"""Initial2

Revision ID: 92bc93576f4b
Revises: 9bdc97dfd191
Create Date: 2025-12-15 18:33:30.512601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92bc93576f4b'
down_revision: Union[str, None] = '9bdc97dfd191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('test_tenant_specific_field', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('new_test', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'new_test')
    op.drop_column('customers', 'test_tenant_specific_field')
    # ### end Alembic commands ###

def check() -> None:
    """check for sync between the tenants and metadata"""
    "pass"
    