"""Initial2

Revision ID: 95a703981e4b
Revises: 06a770853707
Create Date: 2025-12-15 17:03:06.010702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a703981e4b'
down_revision: Union[str, None] = '06a770853707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('new_test', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'new_test')
    # ### end Alembic commands ###

def check() -> None:
    """check for sync between the tenants and metadata"""
    "pass"
    