"""Initial2

Revision ID: 9bdc97dfd191
Revises: 41d6ad80ac73
Create Date: 2025-12-15 17:07:07.592665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bdc97dfd191'
down_revision: Union[str, None] = '41d6ad80ac73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'test_tenant_specific_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('test_tenant_specific_field', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###

def check() -> None:
    """check for sync between the tenants and metadata"""
    "pass"
    