"""public_testing_04

Revision ID: 09b11373c517
Revises: be9be28400f3
Create Date: 2025-12-15 18:34:53.230973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b11373c517'
down_revision: Union[str, None] = 'be9be28400f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('test_public_meta_product', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'test_public_meta_product')
    # ### end Alembic commands ###
