"""public_testing_01

Revision ID: 0a947917dca0
Revises: f64aba2f71e7
Create Date: 2025-12-15 11:36:30.776415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a947917dca0'
down_revision: Union[str, None] = 'f64aba2f71e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('test_public_meta_product', sa.String(length=1), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'test_public_meta_product')
    # ### end Alembic commands ###
