"""public_testing_02

Revision ID: 46616bfc39e7
Revises: 0a947917dca0
Create Date: 2025-12-15 11:42:38.755950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46616bfc39e7'
down_revision: Union[str, None] = '0a947917dca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('has_schema', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_tenants_has_schema'), 'tenants', ['has_schema'], unique=False)
    op.drop_column('tenants', 'test_public_meta_product')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('test_public_meta_product', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tenants_has_schema'), table_name='tenants')
    op.drop_column('tenants', 'has_schema')
    # ### end Alembic commands ###
