"""public_testing_03

Revision ID: be9be28400f3
Revises: 46616bfc39e7
Create Date: 2025-12-15 13:53:21.532043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9be28400f3'
down_revision: Union[str, None] = '46616bfc39e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'has_schema',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'has_schema',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
