"""public_kkkkk

Revision ID: f64aba2f71e7
Revises: 
Create Date: 2025-12-12 18:59:49.428051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f64aba2f71e7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_time', 'system_audit_log', ['action', 'created_at'], unique=False)
    op.create_index('idx_audit_org_time', 'system_audit_log', ['org_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_system_audit_log_action'), 'system_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_system_audit_log_created_at'), 'system_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_system_audit_log_id'), 'system_audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_system_audit_log_org_id'), 'system_audit_log', ['org_id'], unique=False)
    op.create_table('tenant_migration_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=50), nullable=False),
    sa.Column('migration_version', sa.String(length=50), nullable=False),
    sa.Column('migration_name', sa.String(length=255), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('applied_by', sa.String(length=100), nullable=True),
    sa.Column('test_public_meta_product', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenant_migration_history_id'), 'tenant_migration_history', ['id'], unique=False)
    op.create_index(op.f('ix_tenant_migration_history_org_id'), 'tenant_migration_history', ['org_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=50), nullable=False),
    sa.Column('org_name', sa.String(length=255), nullable=False),
    sa.Column('schema_name', sa.String(length=63), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenant_active_schema', 'tenants', ['is_active', 'schema_name'], unique=False)
    op.create_index('idx_tenant_org_lookup', 'tenants', ['org_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_is_active'), 'tenants', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenants_org_id'), 'tenants', ['org_id'], unique=True)
    op.create_index(op.f('ix_tenants_schema_name'), 'tenants', ['schema_name'], unique=True)
    op.create_index(op.f('ix_alembic_version_version_num'), 'alembic_version', ['version_num'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alembic_version_version_num'), table_name='alembic_version')
    op.drop_index(op.f('ix_tenants_schema_name'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_org_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_is_active'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index('idx_tenant_org_lookup', table_name='tenants')
    op.drop_index('idx_tenant_active_schema', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_tenant_migration_history_org_id'), table_name='tenant_migration_history')
    op.drop_index(op.f('ix_tenant_migration_history_id'), table_name='tenant_migration_history')
    op.drop_table('tenant_migration_history')
    op.drop_index(op.f('ix_system_audit_log_org_id'), table_name='system_audit_log')
    op.drop_index(op.f('ix_system_audit_log_id'), table_name='system_audit_log')
    op.drop_index(op.f('ix_system_audit_log_created_at'), table_name='system_audit_log')
    op.drop_index(op.f('ix_system_audit_log_action'), table_name='system_audit_log')
    op.drop_index('idx_audit_org_time', table_name='system_audit_log')
    op.drop_index('idx_audit_action_time', table_name='system_audit_log')
    op.drop_table('system_audit_log')
    # ### end Alembic commands ###
